x-build-template: &a1
    build:
        context: .
        dockerfile: Containerfile
        target: development
        args:
            USER_ID: 1000
            GROUP_ID: 1000
services:
    app:
        <<: *a1
        restart: always
        env_file: .env
        environment:
            - AUTORUN_ENABLED=1
            - PHP_OPCACHE_ENABLE=1
            - XDEBUG_MODE=coverage
            # Publish broadcasts to Reverb over the internal network
            - REVERB_PUBLISH_HOST=reverb
            - REVERB_PUBLISH_PORT=8000
            - REVERB_PUBLISH_SCHEME=http
        volumes:
            - .:/var/www/html
    reverb:
        <<: *a1
        restart: always
        env_file: .env
        environment:
            - PHP_OPCACHE_ENABLE=1
        volumes:
            - .:/var/www/html
        command: ['php', '/var/www/html/artisan', '--port=8000', 'reverb:start']
        stop_signal: SIGTERM
        healthcheck:
            test:
                - CMD
                - healthcheck-reverb
            start_period: 10s
    queue:
        <<: *a1
        restart: always
        env_file: .env
        environment:
            - PHP_OPCACHE_ENABLE=1
            # Publish broadcasts to Reverb over the internal network
            - REVERB_PUBLISH_HOST=reverb
            - REVERB_PUBLISH_PORT=8000
            - REVERB_PUBLISH_SCHEME=http
        command:
            ['php', '/var/www/html/artisan', 'queue:work', '--tries=3', '-vvv']
        stop_signal: SIGTERM
        healthcheck:
            test: ['CMD', 'healthcheck-queue']
            start_period: 10s
        volumes:
            - .:/var/www/html
    scheduler:
        <<: *a1
        restart: always
        env_file: .env
        environment:
            - PHP_OPCACHE_ENABLE=1
        command: ['php', '/var/www/html/artisan', 'schedule:work']
        stop_signal: SIGTERM
        healthcheck:
            test: ['CMD', 'healthcheck-schedule']
            start_period: 10s
        volumes:
            - .:/var/www/html
